export default [[
  {
    key: '`',
    size: 'default',
    shifted: '~',
    keyCode: 'Backquote',
    purpose: 'common',
  },
  {
    key: '1',
    size: 'default',
    shifted: '!',
    keyCode: 'Digit1',
    purpose: 'common',
  },
  {
    key: '2',
    size: 'default',
    shifted: '@',
    keyCode: 'Digit2',
    purpose: 'common',
  },
  {
    key: '3',
    size: 'default',
    shifted: '#',
    keyCode: 'Digit3',
    purpose: 'common',
  },
  {
    key: '4',
    size: 'default',
    shifted: '$',
    keyCode: 'Digit4',
    purpose: 'common',
  },
  {
    key: '5',
    size: 'default',
    shifted: '%',
    keyCode: 'Digit5',
    purpose: 'common',
  },
  {
    key: '6',
    size: 'default',
    shifted: '^',
    keyCode: 'Digit6',
    purpose: 'common',
  },
  {
    key: '7',
    size: 'default',
    shifted: '&',
    keyCode: 'Digit7',
    purpose: 'common',
  },
  {
    key: '8',
    size: 'default',
    shifted: '&',
    keyCode: 'Digit8',
    purpose: 'common',
  },
  {
    key: '9',
    size: 'default',
    shifted: '(',
    keyCode: 'Digit9',
    purpose: 'common',
  },
  {
    key: '0',
    size: 'default',
    shifted: ')',
    keyCode: 'Digit0',
    purpose: 'common',
  },
  {
    key: '-',
    size: 'default',
    shifted: '_',
    keyCode: 'Minus',
    purpose: 'common',
  },
  {
    key: '=',
    size: 'default',
    shifted: '+',
    keyCode: 'Equal',
    purpose: 'common',
  },
  {
    key: '&larr; Backspace',
    size: 'upper-medium',
    shifted: '&larr; Backspace',
    keyCode: 'Backspace',
    purpose: 'special',
  },
],
[
  {
    key: 'Tab',
    size: 'medium',
    shifted: 'Tab',
    keyCode: 'Tab',
    purpose: 'special',
  },
  {
    key: 'q',
    size: 'default',
    shifted: 'Q',
    keyCode: 'KeyQ',
    purpose: 'common',
  },
  {
    key: 'w',
    size: 'default',
    shifted: 'W',
    keyCode: 'KeyW',
    purpose: 'common',
  },
  {
    key: 'e',
    size: 'default',
    shifted: 'E',
    keyCode: 'KeyE',
    purpose: 'common',
  },
  {
    key: 'r',
    size: 'default',
    shifted: 'R',
    keyCode: 'KeyR',
    purpose: 'common',
  },
  {
    key: 't',
    size: 'default',
    shifted: 'T',
    keyCode: 'KeyT',
    purpose: 'common',
  },
  {
    key: 'y',
    size: 'default',
    shifted: 'Y',
    keyCode: 'KeyY',
    purpose: 'common',
  },
  {
    key: 'u',
    size: 'default',
    shifted: 'U',
    keyCode: 'KeyU',
    purpose: 'common',
  },
  {
    key: 'i',
    size: 'default',
    shifted: 'I',
    keyCode: 'KeyI',
    purpose: 'common',
  },
  {
    key: 'o',
    size: 'default',
    shifted: 'O',
    keyCode: 'KeyO',
    purpose: 'common',
  },
  {
    key: 'p',
    size: 'default',
    shifted: 'P',
    keyCode: 'KeyP',
    purpose: 'common',
  },
  {
    key: '[',
    size: 'default',
    shifted: '{',
    keyCode: 'BracketLeft',
    purpose: 'common',
  },
  {
    key: ']',
    size: 'default',
    shifted: '}',
    keyCode: 'BracketRight',
    purpose: 'common',
  },
  {
    key: '\\',
    size: 'medium',
    shifted: '|',
    keyCode: 'Backslash',
    purpose: 'common',
  },
],
[
  {
    key: 'Caps lock',
    size: 'medium',
    shifted: 'Caps lock',
    keyCode: 'CapsLock',
    purpose: 'special',
  },
  {
    key: 'a',
    size: 'default',
    shifted: 'A',
    keyCode: 'KeyA',
    purpose: 'common',
  },
  {
    key: 's',
    size: 'default',
    shifted: 'S',
    keyCode: 'KeyS',
    purpose: 'common',
  },
  {
    key: 'd',
    size: 'default',
    shifted: 'D',
    keyCode: 'KeyD',
    purpose: 'common',
  },
  {
    key: 'f',
    size: 'default',
    shifted: 'F',
    keyCode: 'KeyF',
    purpose: 'common',
  },
  {
    key: 'g',
    size: 'default',
    shifted: 'G',
    keyCode: 'KeyG',
    purpose: 'common',
  },
  {
    key: 'h',
    size: 'default',
    shifted: 'H',
    keyCode: 'KeyH',
    purpose: 'common',
  },
  {
    key: 'j',
    size: 'default',
    shifted: 'J',
    keyCode: 'KeyJ',
    purpose: 'common',
  },
  {
    key: 'k',
    size: 'default',
    shifted: 'K',
    keyCode: 'KeyK',
    purpose: 'common',
  },
  {
    key: 'l',
    size: 'default',
    shifted: 'L',
    keyCode: 'KeyL',
    purpose: 'common',
  },
  {
    key: ':',
    size: 'default',
    shifted: ';',
    keyCode: 'Semicolon',
    purpose: 'common',
  },
  {
    key: "'",
    size: 'default',
    shifted: '"',
    keyCode: 'Quote',
    purpose: 'common',
  },
  {
    key: 'Enter',
    size: 'upper-medium',
    shifted: 'Enter',
    keyCode: 'Enter',
    purpose: 'special',
  },
],
[
  {
    key: 'Shift',
    size: 'upper-medium',
    shifted: 'Shift',
    keyCode: 'ShiftLeft',
    purpose: 'special',
  },
  {
    key: 'z',
    size: 'default',
    shifted: 'Z',
    keyCode: 'KeyZ',
    purpose: 'common',
  },
  {
    key: 'x',
    size: 'default',
    shifted: 'X',
    keyCode: 'KeyX',
    purpose: 'common',
  },
  {
    key: 'c',
    size: 'default',
    shifted: 'C',
    keyCode: 'KeyC',
    purpose: 'common',
  },
  {
    key: 'v',
    size: 'default',
    shifted: 'V',
    keyCode: 'KeyV',
    purpose: 'common',
  },
  {
    key: 'b',
    size: 'default',
    shifted: 'B',
    keyCode: 'KeyB',
    purpose: 'common',
  },
  {
    key: 'n',
    size: 'default',
    shifted: 'N',
    keyCode: 'KeyN',
    purpose: 'common',
  },
  {
    key: 'm',
    size: 'default',
    shifted: 'M',
    keyCode: 'KeyM',
    purpose: 'common',
  },
  {
    key: ',',
    size: 'default',
    shifted: '<',
    keyCode: 'Comma',
    purpose: 'common',
  },
  {
    key: '.',
    size: 'default',
    shifted: '>',
    keyCode: 'Period',
    purpose: 'common',
  },
  {
    key: '/',
    size: 'default',
    shifted: '?',
    keyCode: 'Slash',
    purpose: 'common',
  },
  {
    key: '&uarr;',
    size: 'default',
    shifted: '&uarr;',
    keyCode: 'ArrowUp',
    purpose: 'common',
  },
  {
    key: 'Shift',
    size: 'medium',
    shifted: 'Shift',
    keyCode: 'ShiftRight',
    purpose: 'special',
  },
],
[
  {
    key: 'Ctrl',
    size: 'default',
    shifted: 'Ctrl',
    keyCode: 'ControlLeft',
    purpose: 'special',
  },
  {
    key: 'Win',
    size: 'default',
    shifted: 'Win',
    keyCode: 'OSLeft',
    purpose: 'special',
  },
  {
    key: 'Alt',
    size: 'default',
    shifted: 'Alt',
    keyCode: 'AltLeft',
    purpose: 'special',
  },
  {
    key: 'Space',
    size: 'big',
    shifted: 'Space',
    keyCode: 'Space',
    purpose: 'special',
  },
  {
    key: 'Alt',
    size: 'default',
    shifted: 'Alt',
    keyCode: 'AltRight',
    purpose: 'special',
  },
  {
    key: '&larr;',
    size: 'default',
    shifted: '&larr;',
    keyCode: 'ArrowLeft',
    purpose: 'common',
  },
  {
    key: '&darr;',
    size: 'default',
    shifted: '&darr;',
    keyCode: 'ArrowDown',
    purpose: 'common',
  },
  {
    key: '&rarr;',
    size: 'default',
    shifted: '&rarr;',
    keyCode: 'ArrowRight',
    purpose: 'common',
  },
  {
    key: 'Ctrl',
    size: 'default',
    shifted: 'Ctrl',
    keyCode: 'ControlRight',
    purpose: 'special',
  },
],
];
