export default [[
  {
    key: '`',
    ruKey: 'ё',
    size: 'default',
    shifted: '~',
    ruShifted: 'Ё',
    keyCode: 'Backquote',
    purpose: 'common',
  },
  {
    key: '1',
    size: 'default',
    shifted: '!',
    keyCode: 'Digit1',
    purpose: 'common',
  },
  {
    key: '2',
    size: 'default',
    shifted: '@',
    ruShifted: '"',
    keyCode: 'Digit2',
    purpose: 'common',
  },
  {
    key: '3',
    size: 'default',
    shifted: '#',
    ruShifted: '№',
    keyCode: 'Digit3',
    purpose: 'common',
  },
  {
    key: '4',
    size: 'default',
    shifted: '$',
    ruShifted: ';',
    keyCode: 'Digit4',
    purpose: 'common',
  },
  {
    key: '5',
    size: 'default',
    shifted: '%',
    keyCode: 'Digit5',
    purpose: 'common',
  },
  {
    key: '6',
    size: 'default',
    shifted: '^',
    ruShifted: ':',
    keyCode: 'Digit6',
    purpose: 'common',
  },
  {
    key: '7',
    size: 'default',
    shifted: '&',
    ruShifted: '?',
    keyCode: 'Digit7',
    purpose: 'common',
  },
  {
    key: '8',
    size: 'default',
    shifted: '*',
    keyCode: 'Digit8',
    purpose: 'common',
  },
  {
    key: '9',
    size: 'default',
    shifted: '(',
    keyCode: 'Digit9',
    purpose: 'common',
  },
  {
    key: '0',
    size: 'default',
    shifted: ')',
    keyCode: 'Digit0',
    purpose: 'common',
  },
  {
    key: '-',
    size: 'default',
    shifted: '_',
    keyCode: 'Minus',
    purpose: 'common',
  },
  {
    key: '=',
    size: 'default',
    shifted: '+',
    keyCode: 'Equal',
    purpose: 'common',
  },
  {
    key: '&larr; Backspace',
    size: 'upper-medium',
    shifted: '&larr; Backspace',
    keyCode: 'Backspace',
    purpose: 'special',
  },
],
[
  {
    key: 'Tab',
    size: 'medium',
    shifted: 'Tab',
    keyCode: 'Tab',
    purpose: 'special',
  },
  {
    key: 'q',
    ruKey: 'й',
    size: 'default',
    shifted: 'Q',
    ruShifted: 'Й',
    keyCode: 'KeyQ',
    purpose: 'common',
  },
  {
    key: 'w',
    ruKey: 'ц',
    size: 'default',
    shifted: 'W',
    ruShifted: 'Й',
    keyCode: 'KeyW',
    purpose: 'common',
  },
  {
    key: 'e',
    ruKey: 'у',
    size: 'default',
    shifted: 'E',
    ruShifted: 'У',
    keyCode: 'KeyE',
    purpose: 'common',
  },
  {
    key: 'r',
    ruKey: 'к',
    size: 'default',
    shifted: 'R',
    ruShifted: 'К',
    keyCode: 'KeyR',
    purpose: 'common',
  },
  {
    key: 't',
    ruKey: 'е',
    size: 'default',
    shifted: 'T',
    ruShifted: 'Е',
    keyCode: 'KeyT',
    purpose: 'common',
  },
  {
    key: 'y',
    ruKey: 'н',
    size: 'default',
    shifted: 'Y',
    ruShifted: 'Н',
    keyCode: 'KeyY',
    purpose: 'common',
  },
  {
    key: 'u',
    ruKey: 'г',
    size: 'default',
    shifted: 'U',
    ruShifted: 'Г',
    keyCode: 'KeyU',
    purpose: 'common',
  },
  {
    key: 'i',
    ruKey: 'ш',
    size: 'default',
    shifted: 'I',
    ruShifted: 'Ш',
    keyCode: 'KeyI',
    purpose: 'common',
  },
  {
    key: 'o',
    ruKey: 'щ',
    size: 'default',
    shifted: 'O',
    ruShifted: 'Щ',
    keyCode: 'KeyO',
    purpose: 'common',
  },
  {
    key: 'p',
    ruKey: 'з',
    size: 'default',
    shifted: 'P',
    ruShifted: 'З',
    keyCode: 'KeyP',
    purpose: 'common',
  },
  {
    key: '[',
    ruKey: 'х',
    size: 'default',
    shifted: '{',
    ruShifted: 'Х',
    keyCode: 'BracketLeft',
    purpose: 'common',
  },
  {
    key: ']',
    ruKey: 'ъ',
    size: 'default',
    shifted: '}',
    ruShifted: 'Ъ',
    keyCode: 'BracketRight',
    purpose: 'common',
  },
  {
    key: '\\',
    size: 'medium',
    shifted: '|',
    ruShifted: '/',
    keyCode: 'Backslash',
    purpose: 'common',
  },
],
[
  {
    key: 'Caps lock',
    size: 'medium',
    shifted: 'Caps lock',
    keyCode: 'CapsLock',
    purpose: 'special',
  },
  {
    key: 'a',
    ruKey: 'ф',
    size: 'default',
    shifted: 'A',
    ruShifted: 'Ф',
    keyCode: 'KeyA',
    purpose: 'common',
  },
  {
    key: 's',
    ruKey: 'ы',
    size: 'default',
    shifted: 'S',
    ruShifted: 'Ы',
    keyCode: 'KeyS',
    purpose: 'common',
  },
  {
    key: 'd',
    ruKey: 'в',
    size: 'default',
    shifted: 'D',
    ruShifted: 'В',
    keyCode: 'KeyD',
    purpose: 'common',
  },
  {
    key: 'f',
    ruKey: 'а',
    size: 'default',
    shifted: 'F',
    ruShifted: 'А',
    keyCode: 'KeyF',
    purpose: 'common',
  },
  {
    key: 'g',
    ruKey: 'п',
    size: 'default',
    shifted: 'G',
    ruShifted: 'П',
    keyCode: 'KeyG',
    purpose: 'common',
  },
  {
    key: 'h',
    ruKey: 'р',
    size: 'default',
    shifted: 'H',
    ruShifted: 'Р',
    keyCode: 'KeyH',
    purpose: 'common',
  },
  {
    key: 'j',
    ruKey: 'о',
    size: 'default',
    shifted: 'J',
    ruShifted: 'О',
    keyCode: 'KeyJ',
    purpose: 'common',
  },
  {
    key: 'k',
    ruKey: 'л',
    size: 'default',
    shifted: 'K',
    ruShifted: 'Л',
    keyCode: 'KeyK',
    purpose: 'common',
  },
  {
    key: 'l',
    ruKey: 'д',
    size: 'default',
    shifted: 'L',
    ruShifted: 'Д',
    keyCode: 'KeyL',
    purpose: 'common',
  },
  {
    key: ':',
    ruKey: 'ж',
    size: 'default',
    shifted: ';',
    ruShifted: 'Ж',
    keyCode: 'Semicolon',
    purpose: 'common',
  },
  {
    key: "'",
    ruKey: 'э',
    size: 'default',
    shifted: '"',
    ruShifted: 'Э',
    keyCode: 'Quote',
    purpose: 'common',
  },
  {
    key: 'Enter',
    size: 'upper-medium',
    shifted: 'Enter',
    keyCode: 'Enter',
    purpose: 'special',
  },
],
[
  {
    key: 'Shift',
    size: 'upper-medium',
    shifted: 'Shift',
    keyCode: 'ShiftLeft',
    purpose: 'special',
  },
  {
    key: 'z',
    ruKey: 'я',
    size: 'default',
    shifted: 'Z',
    ruShifted: 'Я',
    keyCode: 'KeyZ',
    purpose: 'common',
  },
  {
    key: 'x',
    ruKey: 'ч',
    size: 'default',
    shifted: 'X',
    ruShifted: 'Ч',
    keyCode: 'KeyX',
    purpose: 'common',
  },
  {
    key: 'c',
    ruKey: 'с',
    size: 'default',
    shifted: 'C',
    ruShifted: 'С',
    keyCode: 'KeyC',
    purpose: 'common',
  },
  {
    key: 'v',
    ruKey: 'м',
    size: 'default',
    shifted: 'V',
    ruShifted: 'М',
    keyCode: 'KeyV',
    purpose: 'common',
  },
  {
    key: 'b',
    ruKey: 'и',
    size: 'default',
    shifted: 'B',
    ruShifted: 'И',
    keyCode: 'KeyB',
    purpose: 'common',
  },
  {
    key: 'n',
    ruKey: 'т',
    size: 'default',
    shifted: 'N',
    ruShifted: 'Т',
    keyCode: 'KeyN',
    purpose: 'common',
  },
  {
    key: 'm',
    ruKey: 'ь',
    size: 'default',
    shifted: 'M',
    ruShifted: 'Ь',
    keyCode: 'KeyM',
    purpose: 'common',
  },
  {
    key: ',',
    ruKey: 'б',
    size: 'default',
    shifted: '<',
    ruShifted: 'Б',
    keyCode: 'Comma',
    purpose: 'common',
  },
  {
    key: '.',
    ruKey: 'ю',
    size: 'default',
    shifted: '>',
    ruShifted: 'Ю',
    keyCode: 'Period',
    purpose: 'common',
  },
  {
    key: '/',
    ruKey: '.',
    size: 'default',
    shifted: '?',
    ruShifted: ',',
    keyCode: 'Slash',
    purpose: 'common',
  },
  {
    key: '&uarr;',
    size: 'default',
    shifted: '&uarr;',
    keyCode: 'ArrowUp',
    purpose: 'common',
  },
  {
    key: 'Shift',
    size: 'medium',
    shifted: 'Shift',
    keyCode: 'ShiftRight',
    purpose: 'special',
  },
],
[
  {
    key: 'Ctrl',
    size: 'default',
    shifted: 'Ctrl',
    keyCode: 'ControlLeft',
    purpose: 'special',
  },
  {
    key: 'Win',
    size: 'default',
    shifted: 'Win',
    keyCode: 'OSLeft',
    purpose: 'special',
  },
  {
    key: 'Alt',
    size: 'default',
    shifted: 'Alt',
    keyCode: 'AltLeft',
    purpose: 'special',
  },
  {
    key: 'Space',
    size: 'big',
    shifted: 'Space',
    keyCode: 'Space',
    purpose: 'special',
  },
  {
    key: 'Alt',
    size: 'default',
    shifted: 'Alt',
    keyCode: 'AltRight',
    purpose: 'special',
  },
  {
    key: '&larr;',
    size: 'default',
    shifted: '&larr;',
    keyCode: 'ArrowLeft',
    purpose: 'common',
  },
  {
    key: '&darr;',
    size: 'default',
    shifted: '&darr;',
    keyCode: 'ArrowDown',
    purpose: 'common',
  },
  {
    key: '&rarr;',
    size: 'default',
    shifted: '&rarr;',
    keyCode: 'ArrowRight',
    purpose: 'common',
  },
  {
    key: 'Ctrl',
    size: 'default',
    shifted: 'Ctrl',
    keyCode: 'ControlRight',
    purpose: 'special',
  },
],
];