export default [[
  {
    key: '`',
    size: 'default',
    shifted: '~',
    keyCode: 'Backquote',
    purpose: 'common',
  },
  {
    key: '1',
    size: 'default',
    shifted: '!',
    keyCode: 'Digit1',
    purpose: 'common',
  },
  {
    key: '2',
    size: 'default',
    shifted: '@',
    keyCode: 'Digit2',
    purpose: 'common',
  },
  {
    key: '3',
    size: 'default',
    shifted: '#',
    keyCode: 'Digit3',
    purpose: 'common',
  },
  {
    key: '4',
    size: 'default',
    shifted: '$',
    keyCode: 'Digit4',
    purpose: 'common',
  },
  {
    key: '5',
    size: 'default',
    shifted: '%',
    keyCode: 'Digit5',
    purpose: 'common',
  },
  {
    key: '6',
    size: 'default',
    shifted: '^',
    keyCode: 'Digit6',
    purpose: 'common',
  },
  {
    key: '7',
    size: 'default',
    shifted: '&',
    keyCode: 'Digit7',
    purpose: 'common',
  },
  {
    key: '8',
    size: 'default',
    shifted: '*',
    keyCode: 'Digit8',
    purpose: 'common',
  },
  {
    key: '9',
    size: 'default',
    shifted: '(',
    keyCode: 'Digit9',
    purpose: 'common',
  },
  {
    key: '0',
    size: 'default',
    shifted: ')',
    keyCode: 'Digit0',
    purpose: 'common',
  },
  {
    key: '-',
    size: 'default',
    shifted: '_',
    keyCode: 'Minus',
    purpose: 'common',
  },
  {
    key: '=',
    size: 'default',
    shifted: '+',
    keyCode: 'Equal',
    purpose: 'common',
  },
  {
    key: '&larr; Backspace',
    size: 'upper-medium',
    shifted: '&larr; Backspace',
    keyCode: 'Backspace',
    purpose: 'special',
  },
],
[
  {
    key: 'Tab',
    size: 'medium',
    shifted: 'Tab',
    keyCode: 'Tab',
    purpose: 'special',
  },
  {
    key: 'й',
    size: 'default',
    shifted: 'Й',
    keyCode: 'KeyQ',
    purpose: 'common',
  },
  {
    key: 'ц',
    size: 'default',
    shifted: 'Ц',
    keyCode: 'KeyW',
    purpose: 'common',
  },
  {
    key: 'у',
    size: 'default',
    shifted: 'У',
    keyCode: 'KeyE',
    purpose: 'common',
  },
  {
    key: 'к',
    size: 'default',
    shifted: 'К',
    keyCode: 'KeyR',
    purpose: 'common',
  },
  {
    key: 'е',
    size: 'default',
    shifted: 'Е',
    keyCode: 'KeyT',
    purpose: 'common',
  },
  {
    key: 'н',
    size: 'default',
    shifted: 'Н',
    keyCode: 'KeyY',
    purpose: 'common',
  },
  {
    key: 'г',
    size: 'default',
    shifted: 'Г',
    keyCode: 'KeyU',
    purpose: 'common',
  },
  {
    key: 'ш',
    size: 'default',
    shifted: 'Ш',
    keyCode: 'KeyI',
    purpose: 'common',
  },
  {
    key: 'х',
    size: 'default',
    shifted: 'Х',
    keyCode: 'KeyO',
    purpose: 'common',
  },
  {
    key: 'з',
    size: 'default',
    shifted: 'З',
    keyCode: 'KeyP',
    purpose: 'common',
  },
  {
    key: 'х',
    size: 'default',
    shifted: 'Х',
    keyCode: 'BracketLeft',
    purpose: 'common',
  },
  {
    key: 'ъ',
    size: 'default',
    shifted: 'Ъ',
    keyCode: 'BracketRight',
    purpose: 'common',
  },
  {
    key: '\\',
    size: 'medium',
    shifted: '|',
    keyCode: 'Backslash',
    purpose: 'common',
  },
],
[
  {
    key: 'Caps lock',
    size: 'medium',
    shifted: 'Caps lock',
    keyCode: 'CapsLock',
    purpose: 'special',
  },
  {
    key: 'ф',
    size: 'default',
    shifted: 'Ф',
    keyCode: 'KeyA',
    purpose: 'common',
  },
  {
    key: 'ы',
    size: 'default',
    shifted: 'Ы',
    keyCode: 'KeyS',
    purpose: 'common',
  },
  {
    key: 'в',
    size: 'default',
    shifted: 'В',
    keyCode: 'KeyD',
    purpose: 'common',
  },
  {
    key: 'а',
    size: 'default',
    shifted: 'А',
    keyCode: 'KeyF',
    purpose: 'common',
  },
  {
    key: 'п',
    size: 'default',
    shifted: 'П',
    keyCode: 'KeyG',
    purpose: 'common',
  },
  {
    key: 'р',
    size: 'default',
    shifted: 'Р',
    keyCode: 'KeyH',
    purpose: 'common',
  },
  {
    key: 'о',
    size: 'default',
    shifted: 'О',
    keyCode: 'KeyJ',
    purpose: 'common',
  },
  {
    key: 'л',
    size: 'default',
    shifted: 'Л',
    keyCode: 'KeyK',
    purpose: 'common',
  },
  {
    key: 'д',
    size: 'default',
    shifted: 'Д',
    keyCode: 'KeyL',
    purpose: 'common',
  },
  {
    key: 'ж',
    size: 'default',
    shifted: 'Ж',
    keyCode: 'Semicolon',
    purpose: 'common',
  },
  {
    key: 'э',
    size: 'default',
    shifted: 'Э',
    keyCode: 'Quote',
    purpose: 'common',
  },
  {
    key: 'Enter',
    size: 'upper-medium',
    shifted: 'Enter',
    keyCode: 'Enter',
    purpose: 'special',
  },
],
[
  {
    key: 'Shift',
    size: 'upper-medium',
    shifted: 'Shift',
    keyCode: 'ShiftLeft',
    purpose: 'special',
  },
  {
    key: 'я',
    size: 'default',
    shifted: 'Я',
    keyCode: 'KeyZ',
    purpose: 'common',
  },
  {
    key: 'ч',
    size: 'default',
    shifted: 'Ч',
    keyCode: 'KeyX',
    purpose: 'common',
  },
  {
    key: 'с',
    size: 'default',
    shifted: 'С',
    keyCode: 'KeyC',
    purpose: 'common',
  },
  {
    key: 'м',
    size: 'default',
    shifted: 'М',
    keyCode: 'KeyV',
    purpose: 'common',
  },
  {
    key: 'и',
    size: 'default',
    shifted: 'И',
    keyCode: 'KeyB',
    purpose: 'common',
  },
  {
    key: 'т',
    size: 'default',
    shifted: 'Т',
    keyCode: 'KeyN',
    purpose: 'common',
  },
  {
    key: 'ь',
    size: 'default',
    shifted: 'Ь',
    keyCode: 'KeyM',
    purpose: 'common',
  },
  {
    key: 'б',
    size: 'default',
    shifted: 'Б',
    keyCode: 'Comma',
    purpose: 'common',
  },
  {
    key: 'ю',
    size: 'default',
    shifted: 'Ю',
    keyCode: 'Period',
    purpose: 'common',
  },
  {
    key: '.',
    size: 'default',
    shifted: ',',
    keyCode: 'Slash',
    purpose: 'common',
  },
  {
    key: '&uarr;',
    size: 'default',
    shifted: '&uarr;',
    keyCode: 'ArrowUp',
    purpose: 'common',
  },
  {
    key: 'Shift',
    size: 'medium',
    shifted: 'Shift',
    keyCode: 'ShiftRight',
    purpose: 'special',
  },
],
[
  {
    key: 'Ctrl',
    size: 'default',
    shifted: 'Ctrl',
    keyCode: 'ControlLeft',
    purpose: 'special',
  },
  {
    key: 'Win',
    size: 'default',
    shifted: 'Win',
    keyCode: 'OSLeft',
    purpose: 'special',
  },
  {
    key: 'Alt',
    size: 'default',
    shifted: 'Alt',
    keyCode: 'AltLeft',
    purpose: 'special',
  },
  {
    key: 'Space',
    size: 'big',
    shifted: 'Space',
    keyCode: 'Space',
    purpose: 'special',
  },
  {
    key: 'Alt',
    size: 'default',
    shifted: 'Alt',
    keyCode: 'AltRight',
    purpose: 'special',
  },
  {
    key: '&larr;',
    size: 'default',
    shifted: '&larr;',
    keyCode: 'ArrowLeft',
    purpose: 'common',
  },
  {
    key: '&darr;',
    size: 'default',
    shifted: '&darr;',
    keyCode: 'ArrowDown',
    purpose: 'common',
  },
  {
    key: '&rarr;',
    size: 'default',
    shifted: '&rarr;',
    keyCode: 'ArrowRight',
    purpose: 'common',
  },
  {
    key: 'Ctrl',
    size: 'default',
    shifted: 'Ctrl',
    keyCode: 'ControlRight',
    purpose: 'special',
  },
],
];
